services:
  - type: web
    name: ppt-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false 